-- AI Database Optimization Agent: scan history + recommendations audit trail.
-- Additive. "table already exists" is treated as already-applied.

CREATE TABLE IF NOT EXISTS optimization_scans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    triggered_by BIGINT UNSIGNED NULL,
    total_tables INT UNSIGNED NOT NULL DEFAULT 0,
    total_rows BIGINT UNSIGNED NOT NULL DEFAULT 0,
    total_size_mb DECIMAL(12,2) NOT NULL DEFAULT 0,
    expired_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    expiring_soon_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    inactive_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    duplicate_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    missing_index_count INT UNSIGNED NOT NULL DEFAULT 0,
    slow_query_count INT UNSIGNED NOT NULL DEFAULT 0,
    orphaned_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    estimated_recovery_mb DECIMAL(12,2) NOT NULL DEFAULT 0,
    notes JSON NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    CONSTRAINT optimization_scans_triggered_by_foreign FOREIGN KEY (triggered_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS optimization_recommendations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    scan_id BIGINT UNSIGNED NOT NULL,
    category VARCHAR(30) NOT NULL,
    operation VARCHAR(20) NOT NULL DEFAULT 'none',
    table_name VARCHAR(255) NOT NULL,
    column_name VARCHAR(255) NULL,
    affected_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    expiration_status VARCHAR(255) NULL,
    action TEXT NOT NULL,
    risk_level ENUM('low','medium','high') NOT NULL DEFAULT 'low',
    estimated_recovery_mb DECIMAL(12,2) NULL,
    where_sql TEXT NULL,
    where_bindings JSON NULL,
    update_values JSON NULL,
    index_sql TEXT NULL,
    sql_preview TEXT NOT NULL,
    rollback_note TEXT NOT NULL,
    status ENUM('pending','approved','rejected','executed') NOT NULL DEFAULT 'pending',
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at TIMESTAMP NULL,
    executed_by BIGINT UNSIGNED NULL,
    executed_at TIMESTAMP NULL,
    executed_count BIGINT UNSIGNED NULL,
    backup_path VARCHAR(255) NULL,
    rejection_reason TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    KEY optimization_recommendations_scan_id_index (scan_id),
    KEY optimization_recommendations_status_index (status),
    KEY optimization_recommendations_category_index (category),
    CONSTRAINT optimization_recommendations_scan_id_foreign FOREIGN KEY (scan_id) REFERENCES optimization_scans (id) ON DELETE CASCADE,
    CONSTRAINT optimization_recommendations_reviewed_by_foreign FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT optimization_recommendations_executed_by_foreign FOREIGN KEY (executed_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
