-- ROOM: live classroom & video learning
-- Safe to run more than once (IF NOT EXISTS guards, duplicate column is skipped).
-- Tables are created parent-first so every foreign key target already exists.

ALTER TABLE `users`
    ADD COLUMN `can_teach` TINYINT(1) NOT NULL DEFAULT 0 AFTER `can_write_research`;

CREATE TABLE IF NOT EXISTS `learning_categories` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `slug` VARCHAR(255) NOT NULL,
    `description` VARCHAR(500) NULL,
    `icon` VARCHAR(60) NULL,
    `position` INT UNSIGNED NOT NULL DEFAULT 0,
    `created_by` BIGINT UNSIGNED NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_categories_slug_unique` (`slug`),
    KEY `learning_categories_position_index` (`position`),
    CONSTRAINT `learning_categories_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_courses` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_category_id` BIGINT UNSIGNED NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `slug` VARCHAR(255) NOT NULL,
    `summary` VARCHAR(1000) NULL,
    `description` TEXT NULL,
    `thumbnail_path` VARCHAR(255) NULL,
    `level` VARCHAR(20) NULL,
    `instructor_id` BIGINT UNSIGNED NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'draft',
    `access` VARCHAR(20) NOT NULL DEFAULT 'open',
    `position` INT UNSIGNED NOT NULL DEFAULT 0,
    `published_at` TIMESTAMP NULL,
    `created_by` BIGINT UNSIGNED NULL,
    `updated_by` BIGINT UNSIGNED NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_courses_slug_unique` (`slug`),
    KEY `learning_courses_status_category_index` (`status`, `learning_category_id`),
    KEY `learning_courses_instructor_index` (`instructor_id`),
    CONSTRAINT `learning_courses_learning_category_id_fk` FOREIGN KEY (`learning_category_id`) REFERENCES `learning_categories` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `learning_courses_instructor_id_fk` FOREIGN KEY (`instructor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_courses_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_courses_updated_by_fk` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_topics` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_course_id` BIGINT UNSIGNED NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` VARCHAR(500) NULL,
    `position` INT UNSIGNED NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    KEY `learning_topics_course_position_index` (`learning_course_id`, `position`),
    CONSTRAINT `learning_topics_learning_course_id_fk` FOREIGN KEY (`learning_course_id`) REFERENCES `learning_courses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_videos` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_category_id` BIGINT UNSIGNED NOT NULL,
    `learning_course_id` BIGINT UNSIGNED NULL,
    `learning_topic_id` BIGINT UNSIGNED NULL,
    `instructor_id` BIGINT UNSIGNED NULL,
    `created_by` BIGINT UNSIGNED NULL,
    `updated_by` BIGINT UNSIGNED NULL,
    `title` VARCHAR(255) NOT NULL,
    `slug` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `tags` JSON NULL,
    `visibility` VARCHAR(20) NOT NULL DEFAULT 'course',
    `status` VARCHAR(20) NOT NULL DEFAULT 'draft',
    `published_at` TIMESTAMP NULL,
    `disk` VARCHAR(30) NULL,
    `path` VARCHAR(255) NULL,
    `original_name` VARCHAR(255) NULL,
    `mime` VARCHAR(100) NULL,
    `size_bytes` BIGINT UNSIGNED NULL,
    `duration_seconds` INT UNSIGNED NULL,
    `width` SMALLINT UNSIGNED NULL,
    `height` SMALLINT UNSIGNED NULL,
    `thumbnail_path` VARCHAR(255) NULL,
    `position` INT UNSIGNED NOT NULL DEFAULT 0,
    `views` INT UNSIGNED NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_videos_slug_unique` (`slug`),
    KEY `learning_videos_status_category_index` (`status`, `learning_category_id`),
    KEY `learning_videos_course_topic_position_index` (`learning_course_id`, `learning_topic_id`, `position`),
    KEY `learning_videos_instructor_index` (`instructor_id`),
    KEY `learning_videos_published_at_index` (`published_at`),
    CONSTRAINT `learning_videos_learning_category_id_fk` FOREIGN KEY (`learning_category_id`) REFERENCES `learning_categories` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `learning_videos_learning_course_id_fk` FOREIGN KEY (`learning_course_id`) REFERENCES `learning_courses` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_videos_learning_topic_id_fk` FOREIGN KEY (`learning_topic_id`) REFERENCES `learning_topics` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_videos_instructor_id_fk` FOREIGN KEY (`instructor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_videos_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_videos_updated_by_fk` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_video_renditions` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_video_id` BIGINT UNSIGNED NOT NULL,
    `quality` VARCHAR(10) NOT NULL,
    `height` SMALLINT UNSIGNED NOT NULL,
    `disk` VARCHAR(30) NOT NULL,
    `path` VARCHAR(255) NOT NULL,
    `mime` VARCHAR(100) NOT NULL,
    `size_bytes` BIGINT UNSIGNED NOT NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_video_renditions_video_quality_unique` (`learning_video_id`, `quality`),
    CONSTRAINT `learning_video_renditions_learning_video_id_fk` FOREIGN KEY (`learning_video_id`) REFERENCES `learning_videos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_video_resources` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_video_id` BIGINT UNSIGNED NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `type` VARCHAR(10) NOT NULL,
    `url` VARCHAR(500) NULL,
    `disk` VARCHAR(30) NULL,
    `path` VARCHAR(255) NULL,
    `original_name` VARCHAR(255) NULL,
    `mime` VARCHAR(100) NULL,
    `size_bytes` BIGINT UNSIGNED NULL,
    `position` INT UNSIGNED NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    KEY `learning_video_resources_video_position_index` (`learning_video_id`, `position`),
    CONSTRAINT `learning_video_resources_learning_video_id_fk` FOREIGN KEY (`learning_video_id`) REFERENCES `learning_videos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_video_progress` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `learning_video_id` BIGINT UNSIGNED NOT NULL,
    `position_seconds` INT UNSIGNED NOT NULL DEFAULT 0,
    `max_position_seconds` INT UNSIGNED NOT NULL DEFAULT 0,
    `watched_seconds` INT UNSIGNED NOT NULL DEFAULT 0,
    `duration_seconds` INT UNSIGNED NULL,
    `percent` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `play_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `completed_at` TIMESTAMP NULL,
    `last_watched_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_video_progress_user_video_unique` (`user_id`, `learning_video_id`),
    KEY `learning_video_progress_user_last_watched_index` (`user_id`, `last_watched_at`),
    KEY `learning_video_progress_video_completed_index` (`learning_video_id`, `completed_at`),
    CONSTRAINT `learning_video_progress_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_video_progress_learning_video_id_fk` FOREIGN KEY (`learning_video_id`) REFERENCES `learning_videos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_video_comments` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_video_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `parent_id` BIGINT UNSIGNED NULL,
    `body` TEXT NOT NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    KEY `learning_video_comments_video_parent_id_index` (`learning_video_id`, `parent_id`, `id`),
    CONSTRAINT `learning_video_comments_learning_video_id_fk` FOREIGN KEY (`learning_video_id`) REFERENCES `learning_videos` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_video_comments_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_video_comments_parent_id_fk` FOREIGN KEY (`parent_id`) REFERENCES `learning_video_comments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_enrollments` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `learning_course_id` BIGINT UNSIGNED NOT NULL,
    `source` VARCHAR(20) NOT NULL DEFAULT 'self',
    `enrolled_by` BIGINT UNSIGNED NULL,
    `enrolled_at` TIMESTAMP NULL,
    `completed_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_enrollments_user_course_unique` (`user_id`, `learning_course_id`),
    KEY `learning_enrollments_course_index` (`learning_course_id`),
    CONSTRAINT `learning_enrollments_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_enrollments_learning_course_id_fk` FOREIGN KEY (`learning_course_id`) REFERENCES `learning_courses` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_enrollments_enrolled_by_fk` FOREIGN KEY (`enrolled_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_rooms` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `slug` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `learning_category_id` BIGINT UNSIGNED NULL,
    `learning_course_id` BIGINT UNSIGNED NULL,
    `learning_topic_id` BIGINT UNSIGNED NULL,
    `host_id` BIGINT UNSIGNED NULL,
    `created_by` BIGINT UNSIGNED NULL,
    `updated_by` BIGINT UNSIGNED NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'draft',
    `access` VARCHAR(20) NOT NULL DEFAULT 'public',
    `scheduled_at` TIMESTAMP NULL,
    `duration_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 60,
    `provider_room` VARCHAR(120) NOT NULL,
    `chat_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `questions_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `allow_participant_media` TINYINT(1) NOT NULL DEFAULT 1,
    `reminder_sent_at` TIMESTAMP NULL,
    `started_at` TIMESTAMP NULL,
    `ended_at` TIMESTAMP NULL,
    `cancel_reason` VARCHAR(500) NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_rooms_slug_unique` (`slug`),
    UNIQUE KEY `learning_rooms_provider_room_unique` (`provider_room`),
    KEY `learning_rooms_status_scheduled_at_index` (`status`, `scheduled_at`),
    KEY `learning_rooms_host_index` (`host_id`),
    CONSTRAINT `learning_rooms_learning_category_id_fk` FOREIGN KEY (`learning_category_id`) REFERENCES `learning_categories` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_rooms_learning_course_id_fk` FOREIGN KEY (`learning_course_id`) REFERENCES `learning_courses` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_rooms_learning_topic_id_fk` FOREIGN KEY (`learning_topic_id`) REFERENCES `learning_topics` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_rooms_host_id_fk` FOREIGN KEY (`host_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_rooms_created_by_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_rooms_updated_by_fk` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_room_members` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_room_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `added_by` BIGINT UNSIGNED NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_room_members_room_user_unique` (`learning_room_id`, `user_id`),
    CONSTRAINT `learning_room_members_learning_room_id_fk` FOREIGN KEY (`learning_room_id`) REFERENCES `learning_rooms` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_room_members_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_room_members_added_by_fk` FOREIGN KEY (`added_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_room_sessions` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_room_id` BIGINT UNSIGNED NOT NULL,
    `started_by` BIGINT UNSIGNED NULL,
    `ended_by` BIGINT UNSIGNED NULL,
    `started_at` TIMESTAMP NULL,
    `ended_at` TIMESTAMP NULL,
    `peak_participants` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    KEY `learning_room_sessions_room_started_at_index` (`learning_room_id`, `started_at`),
    CONSTRAINT `learning_room_sessions_learning_room_id_fk` FOREIGN KEY (`learning_room_id`) REFERENCES `learning_rooms` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_room_sessions_started_by_fk` FOREIGN KEY (`started_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_room_sessions_ended_by_fk` FOREIGN KEY (`ended_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_room_attendances` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_room_session_id` BIGINT UNSIGNED NOT NULL,
    `learning_room_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `role` VARCHAR(20) NOT NULL DEFAULT 'participant',
    `first_joined_at` TIMESTAMP NULL,
    `last_seen_at` TIMESTAMP NULL,
    `left_at` TIMESTAMP NULL,
    `total_seconds` INT UNSIGNED NOT NULL DEFAULT 0,
    `join_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `removed_at` TIMESTAMP NULL,
    `removed_by` BIGINT UNSIGNED NULL,
    `jitsi_participant_id` VARCHAR(64) NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_room_attendances_session_user_unique` (`learning_room_session_id`, `user_id`),
    KEY `learning_room_attendances_room_user_index` (`learning_room_id`, `user_id`),
    CONSTRAINT `learning_room_attendances_learning_room_session_id_fk` FOREIGN KEY (`learning_room_session_id`) REFERENCES `learning_room_sessions` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_room_attendances_learning_room_id_fk` FOREIGN KEY (`learning_room_id`) REFERENCES `learning_rooms` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_room_attendances_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_room_attendances_removed_by_fk` FOREIGN KEY (`removed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_room_messages` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_room_id` BIGINT UNSIGNED NOT NULL,
    `learning_room_session_id` BIGINT UNSIGNED NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `type` VARCHAR(20) NOT NULL DEFAULT 'chat',
    `body` TEXT NOT NULL,
    `is_answered` TINYINT(1) NOT NULL DEFAULT 0,
    `answered_by` BIGINT UNSIGNED NULL,
    `answered_at` TIMESTAMP NULL,
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    KEY `learning_room_messages_room_id_index` (`learning_room_id`, `id`),
    KEY `learning_room_messages_room_updated_at_index` (`learning_room_id`, `updated_at`),
    CONSTRAINT `learning_room_messages_learning_room_id_fk` FOREIGN KEY (`learning_room_id`) REFERENCES `learning_rooms` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_room_messages_learning_room_session_id_fk` FOREIGN KEY (`learning_room_session_id`) REFERENCES `learning_room_sessions` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_room_messages_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_room_messages_answered_by_fk` FOREIGN KEY (`answered_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `learning_room_recordings` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `learning_room_id` BIGINT UNSIGNED NOT NULL,
    `learning_room_session_id` BIGINT UNSIGNED NULL,
    `source` VARCHAR(20) NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'ready',
    `disk` VARCHAR(30) NULL,
    `path` VARCHAR(255) NULL,
    `original_name` VARCHAR(255) NULL,
    `mime` VARCHAR(100) NULL,
    `size_bytes` BIGINT UNSIGNED NULL,
    `duration_seconds` INT UNSIGNED NULL,
    `external_id` VARCHAR(191) NULL,
    `external_url` TEXT NULL,
    `error` TEXT NULL,
    `is_shared` TINYINT(1) NOT NULL DEFAULT 0,
    `learning_video_id` BIGINT UNSIGNED NULL,
    `uploaded_by` BIGINT UNSIGNED NULL,
    `created_at` TIMESTAMP NULL,
    `updated_at` TIMESTAMP NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `learning_room_recordings_external_id_unique` (`external_id`),
    KEY `learning_room_recordings_room_index` (`learning_room_id`),
    CONSTRAINT `learning_room_recordings_learning_room_id_fk` FOREIGN KEY (`learning_room_id`) REFERENCES `learning_rooms` (`id`) ON DELETE CASCADE,
    CONSTRAINT `learning_room_recordings_learning_room_session_id_fk` FOREIGN KEY (`learning_room_session_id`) REFERENCES `learning_room_sessions` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_room_recordings_learning_video_id_fk` FOREIGN KEY (`learning_video_id`) REFERENCES `learning_videos` (`id`) ON DELETE SET NULL,
    CONSTRAINT `learning_room_recordings_uploaded_by_fk` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
