-- Add staff, contracts, and payroll foundation tables for the Finance module.
CREATE TABLE IF NOT EXISTS `finance_departments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `finance_departments_code_unique` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `finance_employment_types` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `finance_employment_types_code_unique` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `finance_positions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `finance_department_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NULL,
  `salary_grade` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `finance_positions_code_unique` (`code`),
  KEY `finance_positions_finance_department_id_foreign` (`finance_department_id`),
  CONSTRAINT `finance_positions_finance_department_id_foreign` FOREIGN KEY (`finance_department_id`) REFERENCES `finance_departments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `finance_staff` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `staff_number` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(255) NULL,
  `date_of_birth` DATE NULL,
  `national_id` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `alternative_phone` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `region` VARCHAR(255) NULL,
  `district` VARCHAR(255) NULL,
  `emergency_contact` VARCHAR(255) NULL,
  `emergency_contact_phone` VARCHAR(255) NULL,
  `finance_department_id` BIGINT UNSIGNED NULL,
  `finance_position_id` BIGINT UNSIGNED NULL,
  `finance_employment_type_id` BIGINT UNSIGNED NULL,
  `hire_date` DATE NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `basic_salary` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `bank_name` VARCHAR(255) NULL,
  `bank_account_number` VARCHAR(255) NULL,
  `mobile_money` VARCHAR(255) NULL,
  `tax_number` VARCHAR(255) NULL,
  `pension_number` VARCHAR(255) NULL,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `finance_staff_staff_number_unique` (`staff_number`),
  KEY `finance_staff_status_finance_department_id_index` (`status`, `finance_department_id`),
  KEY `finance_staff_finance_department_id_foreign` (`finance_department_id`),
  KEY `finance_staff_finance_position_id_foreign` (`finance_position_id`),
  KEY `finance_staff_finance_employment_type_id_foreign` (`finance_employment_type_id`),
  KEY `finance_staff_created_by_foreign` (`created_by`),
  CONSTRAINT `finance_staff_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `finance_staff_finance_department_id_foreign` FOREIGN KEY (`finance_department_id`) REFERENCES `finance_departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `finance_staff_finance_employment_type_id_foreign` FOREIGN KEY (`finance_employment_type_id`) REFERENCES `finance_employment_types` (`id`) ON DELETE SET NULL,
  CONSTRAINT `finance_staff_finance_position_id_foreign` FOREIGN KEY (`finance_position_id`) REFERENCES `finance_positions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `finance_staff_contracts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `finance_staff_id` BIGINT UNSIGNED NOT NULL,
  `finance_department_id` BIGINT UNSIGNED NULL,
  `finance_position_id` BIGINT UNSIGNED NULL,
  `finance_employment_type_id` BIGINT UNSIGNED NULL,
  `contract_number` VARCHAR(255) NOT NULL,
  `contract_type` VARCHAR(255) NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `probation_end_date` DATE NULL,
  `basic_salary` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `salary_grade` VARCHAR(255) NULL,
  `leave_entitlement_days` SMALLINT UNSIGNED NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'draft',
  `renewal_date` DATE NULL,
  `termination_date` DATE NULL,
  `termination_reason` TEXT NULL,
  `notes` TEXT NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `finance_staff_contracts_contract_number_unique` (`contract_number`),
  KEY `finance_staff_contracts_status_end_date_index` (`status`, `end_date`),
  KEY `finance_staff_contracts_finance_staff_id_foreign` (`finance_staff_id`),
  KEY `finance_staff_contracts_finance_department_id_foreign` (`finance_department_id`),
  KEY `finance_staff_contracts_finance_position_id_foreign` (`finance_position_id`),
  KEY `finance_staff_contracts_finance_employment_type_id_foreign` (`finance_employment_type_id`),
  KEY `finance_staff_contracts_created_by_foreign` (`created_by`),
  CONSTRAINT `finance_staff_contracts_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `finance_staff_contracts_finance_department_id_foreign` FOREIGN KEY (`finance_department_id`) REFERENCES `finance_departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `finance_staff_contracts_finance_employment_type_id_foreign` FOREIGN KEY (`finance_employment_type_id`) REFERENCES `finance_employment_types` (`id`) ON DELETE SET NULL,
  CONSTRAINT `finance_staff_contracts_finance_position_id_foreign` FOREIGN KEY (`finance_position_id`) REFERENCES `finance_positions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `finance_staff_contracts_finance_staff_id_foreign` FOREIGN KEY (`finance_staff_id`) REFERENCES `finance_staff` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `finance_payroll_periods` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `period_month` DATE NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'draft',
  `staff_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `gross_pay` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `total_deductions` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `net_pay` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `finance_payroll_periods_period_month_unique` (`period_month`),
  KEY `finance_payroll_periods_created_by_foreign` (`created_by`),
  CONSTRAINT `finance_payroll_periods_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
