-- Mobile money gateway attempts (AzamPay, ClickPesa): one row per USSD push sent to a customer.
CREATE TABLE IF NOT EXISTS `gateway_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `payment_id` BIGINT UNSIGNED NULL,
  `gateway` VARCHAR(255) NOT NULL,
  `network` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(14,2) NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'TZS',
  `external_id` VARCHAR(255) NOT NULL,
  `provider_transaction_id` VARCHAR(255) NULL,
  `provider_reference` VARCHAR(255) NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `message` VARCHAR(255) NULL,
  `callback_payload` TEXT NULL,
  `completed_at` TIMESTAMP NULL,
  `last_checked_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `gateway_payments_external_id_unique` (`external_id`),
  KEY `gateway_payments_status_created_at_index` (`status`, `created_at`),
  KEY `gateway_payments_order_id_status_index` (`order_id`, `status`),
  KEY `gateway_payments_user_id_foreign` (`user_id`),
  KEY `gateway_payments_payment_id_foreign` (`payment_id`),
  CONSTRAINT `gateway_payments_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `gateway_payments_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `gateway_payments_payment_id_foreign` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
